name: Deploy Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

env:
  VITEPRESS_SITE_URL: https://blog.lonemonk.xyz
  WALINE_SERVER_URL: https://waline-ten-coral.vercel.app

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git Configuration
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: docs/.vitepress/dist
          # cname 参数在v4中已不支持，在GitHub Pages设置中配置自定义域名
